### PR TITLE
Fix conflict with harai/indent-guide-improved

### PR DESCRIPTION
**Pull request by harai**
Though I'm really not sure which package should be fixed, I've created a PR to avoid the conflict with harai/indent-guide-improved.

Some tests still fail.

#79  harai/indent-guide-improved#18

### CODE REVIEW

**Comment by DavidLGoldberg** [comment]
@harai .

Wow, thanks for the help.

I'm actually completely rewriting that *part* of the code.  I'm going to be using markers+decorators.

I only have one small bug to work through, but should be out in the next couple of days.

I didn't realize what the conflict was.  It looks like something to do with the container and the shadow?  What exactly does your commit fix, could you give me a little more insight.  Might affect how I finish up my new branch.

Also despite your changes looking cleaner (again, that code goes away with new branch), should your package really be breakable like that?  Can you link me to the part that breaks in yours maybe we can make your package stronger while we're at it too!  I actually had that idea and wanted to make it, then heard about yours :+1: 

Oh, if you'd like to check out the new branch its:
https://github.com/DavidLGoldberg/jumpy/tree/use_markers_and_decorations

(I'll get your package and check it too in the next few days)

**Comment by harai** [comment]
The fix is about [Web Components](https://developer.mozilla.org/en-US/docs/Web/Web_Components).

In the world of Web Components, inserting elements directly under `content` isn't the right way to add the content.  Instead, you should create elements which _point to_ the point you want to insert to using `class` attributes, and then insert them just outside the Shadow DOM.

**Comment by DavidLGoldberg** [comment]
Yes, I know and use web components etc.

I was intentionally writing to the shadow.. to get to the .overlayer (existing, not mine).

That said, that code was architected / written before the Atom dom was all abstracted out as custom elements (a long time ago).

I probably could / should if anything have my own overlayer, but the need for an overlayer goes away completely in my new branch because it uses markers/decorators (linked above).  Going to keep trying to finish that.

**Comment by DavidLGoldberg** [comment]
So like writing to the shadow was kind of a hack, to just keep things business as usual.

**Comment by brandon-fryslie** [comment]
To anyone who comes by to check on the status of this issue, you can fix this currently by removing jumpy, manually installing the package from harai's forked repo repo (instructions for installing an atom package from a repo here: https://github.com/atom/apm/issues/355), and checking out the SHA of the commit attached to this issue.

**Comment by DavidLGoldberg** [comment]
Hey, everyone.  As I expected, the new release has no issue (that I can tell) with this package.  I've installed it and love it already.  It also totally helps see where you're going with Jumpy, as the beacon stopped working again several releases ago (I'll try to get around to that eventually).  Anyway @harai Thanks for the awesome package!

If you think there are *still* some issues please let me know, I can probably make simple tweaks faster now that the large release is done.

**Pull request closed without merging**
