### PR TITLE
replaced deprecated selectors

### PR DESCRIPTION
**Pull request by badem4o**
replaced deprecated .workspace and .editor selectors with atom-workseace and atom-text-editor tags

### CODE REVIEW

**Comment by DavidLGoldberg** [comment]
hmm, so I merged this in, and went live with it (v. 2.0.3), but for some reason it doesn't yet list you as a contributor in jumpy, maybe it's running on some cron job.

-David

**Comment by DavidLGoldberg** [comment]
Thanks for the PR!

**Comment by DavidLGoldberg** [comment]
Was kind of curious why github didn't attribute you.  I noticed that in this link:
https://github.com/DavidLGoldberg/jumpy/commit/6fd5329d7ec69a290627e65634a0e2d22324105f

You'll see your commit has a '?' icon next to it.  It indicates you don't have that email associated with github.  That's why you're not listed in contributors.  Maybe you can add that (if you want to) and see if it updates.  Also, maybe we can make a CONTRIBUTORS.md and add you to it :)  with a valid email.

(Only if you want of course!)

**Comment by badem4o** [comment]
Thanks David,
I appreciate the effort. It seems to be working now that I updated my email address.

**Comment by DavidLGoldberg** [comment]
cool, now I see your icon!  Hopefully the contributors will update. I think I've seen this take a while before.

**Comment by DavidLGoldberg** [comment]
FYI, Just randomly noticed you're no longer listed as a contributor :-(

**Pull request merged**
